##################################################################
### after sva: add svs to linear model                         ###
### this is for complete remission in asthma remission project ###
### we have 3 svs generated by sva                             ###
### Cancan Qi 16/02/2018                                       ###
##################################################################

rm(list=ls())

library(compare)
library(data.table)# to process results
library(MASS) # rlm function for robust linear regression
library(sandwich) #Huber??s estimation of the standard error
library(lmtest) # to use coeftest
library(parallel) # to use multicore approach - part of base R
library(R.utils)

setwd("/home/p282473/projects/asthma_remission/")

load("data/beta_BBRMI.Rdata")
tissue = "brush"
remission="complete_remission"
filename<- paste0("asthma_model1_",tissue,"_",remission,".txt")
samplename<- tolower(colnames(betan))
tissue.index<- grep(tissue,samplename)
beta_matrix<- t(betan[, tissue.index])
rm(betan)
samplename.tissue<- tolower(rownames(beta_matrix))

setwd("./sva")
load("./sva_com_remission.Rdata") # read the sva results 
PHENO<-modSv1
beta_matrix<-beta_matrix[match(tolower(rownames(PHENO)),tolower(rownames(beta_matrix))),]

RLMtest = function(meth_matrix,methcol,remission, X1, X2, X3,X4,X5,X6,S1) {
  mod = rlm(meth_matrix[, methcol] ~ remission+X1+X2+X3+X4+X5+X6+S1,maxit=200)
  cf = try(coeftest(mod, vcov=vcovHC(mod, type="HC0"))) 
  if (class(cf)=="try-error") {
    bad <- as.numeric(rep(NA, 3))
    names(bad)<- c("Estimate", "Std. Error", "Pr(>|z|)")
    bad
  }
  else cf[2, c("Estimate", "Std. Error", "Pr(>|z|)")]   
}

system.time(ind.res <- mclapply(setNames(seq_len(ncol(beta_matrix)), dimnames(beta_matrix)[[2]]), RLMtest, meth_matrix=beta_matrix, remission=PHENO[,1], X1=PHENO[,2], X2=as.factor(PHENO[,3]), X3=PHENO[,4], X4=PHENO[,5], X5=PHENO[,6], X6=PHENO[,7],S1=PHENO[,8]))

setattr(ind.res, 'class', 'data.frame')
setattr(ind.res, "row.names", c(NA_integer_,4))
setattr(ind.res, "names", make.names(names(ind.res), unique=TRUE))
probelistnames <- names(ind.res)
all.results <- t(data.table(ind.res))
all.results<-data.table(all.results)
all.results[, probeID := probelistnames]
setnames(all.results, c("BETA","SE", "P_VAL", "probeID")) # rename columns
setcolorder(all.results, c("probeID","BETA","SE", "P_VAL"))
rm(probelistnames, ind.res)

# export table of results

write.table(all.results, filename,na="NA")
gzip(filename)

